### ISSUE TITLE
시즌별 추천문제

### ISSUE THREAD

**Issue by GHeeJeon** [INU-Fake-Developers/INU-Fake-Developers#1]
## 시즌 1

입출력: [10992](https://www.acmicpc.net/problem/10992) [11718](https://www.acmicpc.net/problem/11718)
정렬: [1181](https://www.acmicpc.net/problem/1181) [2750](https://www.acmicpc.net/problem/2750)
이분탐색: [2805](https://www.acmicpc.net/problem/2805) [11662](https://www.acmicpc.net/problem/11662)
힙: [2075](https://www.acmicpc.net/problem/2075) [11004](https://www.acmicpc.net/problem/11004)
DFS: [2606](https://www.acmicpc.net/problem/2606) [6603](https://www.acmicpc.net/problem/6603)
BFS: [1303](https://www.acmicpc.net/problem/1303) [2178](https://www.acmicpc.net/problem/2178)
완전탐색: [1062](https://www.acmicpc.net/problem/1062) [3085](https://www.acmicpc.net/problem/3085)
그리디: [1931](https://www.acmicpc.net/problem/1931) [13305](https://www.acmicpc.net/problem/13305)
BST: [5639](https://www.acmicpc.net/problem/5639) [9934](https://www.acmicpc.net/problem/9934)
그래프: [4963](https://www.acmicpc.net/problem/4963) [11724](https://www.acmicpc.net/problem/11724)
DP: [1149](https://www.acmicpc.net/problem/1149) [1463](https://www.acmicpc.net/problem/1463) [2579](https://www.acmicpc.net/problem/2579) [9095](https://www.acmicpc.net/problem/9095)

**Comment by potados99** [comment]
><

**Comment by GHeeJeon** [comment]
## 시즌 2
||순한 맛|중간 맛|매운 맛|
|:---:|:---:|:---:|:---:|
|**10<sub>(2)</sub>주차**|9498 10171|2438|1931 11399 11650|
|**11<sub>(2)</sub>주차**|2747 10990|2163|2110 2751 11725|
|**100<sub>(2)</sub>주차**|2753 14681|2741|1260 1697 2178|
|**101<sub>(2)</sub>주차**|10818 1110|11720|1012 2606 4963|
|**110<sub>(2)</sub>주차**|1085 10872|2869|1149 2667 11279|

**Comment by GHeeJeon** [comment]
## 시즌 3
정렬 : 11656번 / 5052번
탐색 : 2503번 / 1062번
그리디 : 1931번 / 1339번
정렬(2) : 1764번 / 1744번
이분탐색 : 2805번 / 2470번
트리 : 1991번 / 1068번
dfs : 2468번 / 1987번
bfs : 1697번 / 2206번
완전탐색 : 3085번 / 14500번
dfs(2) : 2606번 / 10026번
bfs(2) : 2606번 / 14502번
동적계획법 : 1463번 / 9251번
완전탐색(2): 3085번 / 14500번
