### ISSUE TITLE
readme 샘플 만들기!

### ISSUE THREAD

**Issue by GHeeJeon** [INU-Fake-Developers/INU-Fake-Developers#2]
복사해서 갖다 쓸 수 있는 샘플이 있으면 좋을 것 같다!
그래 실드!!! 뱃지?
- [x] 실드(뱃지)
- [ ] 이미지 추가
- [x] 리드미 만드는 사이트 링크 추가

**Comment by GHeeJeon** [comment]
- [ ] 메인 리드미?에 링크를 걸어두자
- [ ] 어떻게 리드미 raw에 접근하는지 써둘 것

**Comment by GHeeJeon** [comment]
raw파일에 접근할 필요 없이 바로 복붙 가능하게! 이름하여 `리드미 팔레트(🎨 )` !
- [ ] 좀 더 가독성 좋게 만들 방법 없을까? 글자색을 바꿀 수 있다면 좋을텐데...
- [ ] 표 추가하기, bullet 추가하기 등등 추가하기

**Comment by ksmfou98** [comment]
샘플자료 감사합니다 ㅎㅎ

**Comment by GHeeJeon** [comment]
> 샘플자료 감사합니다 ㅎㅎ

유용한데 빠진 것이 있다면 언제든 알려주세요~

**Comment by GHeeJeon** [comment]
그래 실드!!! 뱃지?
- [ ] 실드(뱃지)
- [ ] 이미지 추가

**Comment by GHeeJeon** [comment]
https://shields.io/ 실드 만들기
근데 팔레트마냥 갖다쓰기 복잡한데... 좋은 방법 없을까

**Comment by GHeeJeon** [comment]
우선 이 정도만 하고, 중요한 게 떠오르면 다시 오픈하자
