### ISSUE TITLE
앞으로의 스터디 - 시즌 2

### ISSUE THREAD

**Issue by GHeeJeon** [INU-Fake-Developers/INU-Fake-Developers#5]
1. 추후 번외 스터디를 또 할 예정인가?
2. 하게 된다면 파이썬 외 다른 언어도 다룰 것인가?
3. 백준 문제 난이도별 분류(순한 맛 - 3문제, 도전 해볼만한 맛 - 1문제, 매운 맛 - 2문제)
4. 스터디의 존재 목적과 목표를 분명히 할 것.

**Comment by GHeeJeon** [comment]
유닛으로 쪼개? 그룹화?

**Comment by potados99** [comment]
> 추후 번외 스터디를 또 할 예정인가?

역량 되는대로 + 수요 응답형으로 해볼까요!

> 하게 된다면 파이썬 외 다른 언어도 다룰 것인가?

물로니져!

> 백준 문제 난이도별 분류(순한 맛 - 3, 도전 해볼만한 맛 - 1, 매운 맛 - 2)

저는 1번...ㅎㅎ

> 스터디의 존재 목적과 목표를 분명히 할 것.

이게 제일 중요하네요..! 일단 현재는 `코드 버전관리`/`알고리즘 기반 문제해결` 모임이죠! 이 목적을 해치지 않는다면 & 역량만 된다면 추가적인 활동(각각의 유닛에서)을 진행하는 것두 좋다구 생각해요!

**Comment by GHeeJeon** [comment]
> 백준 문제 난이도별 분류(순한 맛 - 3문제, 도전 해볼만한 맛 - 1문제, 매운 맛 - 2문제)
7일 3솔을 원칙으로 하되, 개인 역량에 따라 난이도를 자유롭게 고를 수 있음
사다리타기 해서 일주일에 3명 문제풀이 발표(난이도 상관 X) 당첨자가 6문제중 한 문제를 골라 발표한다.
전원 6문제중 세 문제 이상을 풀어야 한다(일주일 기준)

> 스터디의 존재 목적과 목표를 분명히 할 것.
단기간의 스터디를 통해 비약적 성장을 이루긴 어렵다. (몇백 솔, 많은 시간과 노력이 필요)
어떤 식으로, 어떤 공부를 어떻게 해야하는지를 알아가는 스터디

**Comment by GHeeJeon** [comment]
디코 봇 만들기?

**Comment by GHeeJeon** [comment]
> 번외 스터디 - 디코 봇 만들기?

아니! 수박게임 만들기!

**Comment by GHeeJeon** [comment]
시즌 2 종료! 시즌 3는 따로 고민해보자
